# Generated by Django 2.2.6 on 2019-10-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('customer_income_group', models.CharField(choices=[('0- $25K', '0- $25K'), ('$25-$70K', '$25-$70K'), ('>$70K', '>$70K')], max_length=10)),
                ('customer_region', models.CharField(choices=[('North', 'N'), ('South', 'S'), ('East', 'E'), ('West', 'W')], max_length=10)),
                ('customer_marital_status', models.CharField(choices=[(True, 1), (False, 0)], max_length=1)),
            ],
        ),
    ]
