# Generated by Django 2.2.6 on 2019-10-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_sales', '0002_auto_20191005_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('OTHER', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_income_group',
            field=models.CharField(choices=[('L', '0- $25K'), ('M', '$25-$70K'), ('U', '>$70K')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_region',
            field=models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], max_length=1),
        ),
    ]
