# Generated by Django 2.2.6 on 2019-10-05 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_sales', '0003_auto_20191005_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecords',
            fields=[
                ('sales_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date_of_purchase', models.DateTimeField(blank=True, null=True)),
                ('fuel', models.CharField(choices=[('C', 'CNG'), ('P', 'Petrol'), ('D', 'Diesel')], max_length=1)),
                ('vehicle_segment', models.CharField(max_length=1)),
                ('selling_price', models.IntegerField()),
                ('power_steering', models.CharField(choices=[(True, 1), (False, 0)], max_length=1)),
                ('air_bugs', models.CharField(choices=[(True, 1), (False, 0)], max_length=1)),
                ('sun_roof', models.CharField(choices=[(True, 1), (False, 0)], max_length=1)),
                ('Matt_finish', models.CharField(choices=[(True, 1), (False, 0)], max_length=1)),
                ('music_system', models.CharField(choices=[(True, 1), (False, 0)], max_length=1)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car_sales.Customer')),
            ],
        ),
    ]
