# Generated by Django 2.2.6 on 2019-10-05 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_sales', '0004_salesrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecords',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_sales.Customer'),
        ),
    ]
