# Generated by Django 2.2.6 on 2019-10-08 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_sales', '0007_auto_20191009_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecords',
            name='Matt_finish',
            field=models.CharField(blank=True, choices=[('Yes', 1), ('No', 0)], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecords',
            name='air_bugs',
            field=models.CharField(blank=True, choices=[('Yes', 1), ('No', 0)], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecords',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car_sales.Customer'),
        ),
        migrations.AlterField(
            model_name='salesrecords',
            name='fuel',
            field=models.CharField(blank=True, choices=[('C', 'CNG'), ('P', 'Petrol'), ('D', 'Diesel')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecords',
            name='music_system',
            field=models.CharField(blank=True, choices=[('Yes', 1), ('No', 0)], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecords',
            name='power_steering',
            field=models.CharField(blank=True, choices=[('Yes', 1), ('No', 0)], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecords',
            name='selling_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecords',
            name='sun_roof',
            field=models.CharField(blank=True, choices=[('Yes', 1), ('No', 0)], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecords',
            name='vehicle_segment',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
